/**
 * PaletteLive - Injector
 * Handles CSS injection for live editing.
 */

// Guard against re-injection - use version to allow updates
(() => {
    const _INJECTOR_VERSION = 2;
    if (window._injectorVersion === _INJECTOR_VERSION) {
        return; // Already loaded with same version
    }
    window._injectorVersion = _INJECTOR_VERSION;

    const Injector = {
        styleId: 'palettelive-overrides',

        /**
         * Initialize override stylesheet
         */
        init: () => {
            let style = document.getElementById(Injector.styleId);
            if (!style) {
                style = document.createElement('style');
                style.id = Injector.styleId;
                document.head.appendChild(style);
            }
        },

        state: {
            variables: {},
            selectors: {},
        },

        /**
         * Apply overrides
         * @param {Object} overrides - key-value pairs of CSS variables or selectors
         */
        /**
         * Sanitize a CSS variable name to prevent injection.
         * Only allows valid custom property names: --[a-zA-Z0-9-_]+
         */
        _sanitizeVarName: (name) => {
            if (typeof name !== 'string') return null;
            // Must start with -- and contain only safe characters
            if (!/^--[a-zA-Z0-9_-]+$/.test(name)) return null;
            return name;
        },

        /**
         * Sanitize a CSS value to prevent injection.
         * Strips characters that could break out of a CSS declaration and
         * blocks dangerous CSS constructs like url(javascript:), expression(),
         * -moz-binding, and var() injection chains.
         */
        _sanitizeCSSValue: (value) => {
            if (typeof value !== 'string') return null;
            // Remove characters that could escape the CSS context
            // Block: { } ; < > " \n \r ( ) ' ` and backslash-based escape sequences
            const safe = value.replace(/[{}<>;"\\\n\r()'\`]/g, '').trim();
            if (!safe) return null;
            // Block dangerous CSS constructs (case-insensitive)
            const lower = safe.toLowerCase();
            if (
                lower.includes('url') ||
                lower.includes('expression') ||
                lower.includes('-moz-binding') ||
                lower.includes('behavior') ||
                lower.includes('javascript') ||
                lower.includes('@import') ||
                lower.includes('\\')
            )
                return null;
            return safe;
        },

        /**
         * Sanitize a CSS selector to prevent injection.
         * Only allows class selectors (`.classname`) used by PaletteLive.
         */
        _sanitizeSelector: (selector) => {
            if (typeof selector !== 'string') return null;
            // Strictly allowlist safe classes generated by PaletteLive
            if (
                !/^(?:\.pl-[a-zA-Z0-9-]+)(?:::?(?:hover|focus|active|before|after|focus-visible|focus-within))?$/.test(
                    selector
                )
            )
                return null;
            return selector;
        },

        /**
         * Sanitize a CSS property name.
         * Only allows known CSS property names (lowercase with hyphens).
         */
        _sanitizePropName: (prop) => {
            if (typeof prop !== 'string') return null;
            if (!/^[a-z-]+$/.test(prop)) return null;
            return prop;
        },

        apply: (overrides) => {
            if (!overrides) overrides = {};
            Injector.init();

            // Merge state — variables are flat key/value, shallow merge is fine
            if (overrides.variables) {
                Object.assign(Injector.state.variables, overrides.variables);
            }
            // Selectors are nested { selector: { prop: value } } — deep-merge
            // per selector so existing properties are preserved when adding new ones
            if (overrides.selectors) {
                for (const [selector, rules] of Object.entries(overrides.selectors)) {
                    if (!Injector.state.selectors[selector]) {
                        Injector.state.selectors[selector] = {};
                    }
                    Object.assign(Injector.state.selectors[selector], rules);
                }
            }

            const style = document.getElementById(Injector.styleId);
            if (!style) return;
            let css = ':root {\n';

            // Handle CSS Variables — sanitize both name and value
            for (const [key, value] of Object.entries(Injector.state.variables)) {
                const safeName = Injector._sanitizeVarName(key);
                const safeValue = Injector._sanitizeCSSValue(value);
                if (safeName !== null && safeValue !== null) {
                    css += `  ${safeName}: ${safeValue} !important;\n`;
                }
            }

            css += '}\n';

            // Handle specific selector overrides — sanitize selector, prop, and value
            for (const [selector, rules] of Object.entries(Injector.state.selectors)) {
                const safeSelector = Injector._sanitizeSelector(selector);
                if (!safeSelector) continue;
                css += `${safeSelector} {\n`;
                for (const [prop, val] of Object.entries(rules)) {
                    const safeProp = Injector._sanitizePropName(prop);
                    const safeVal = Injector._sanitizeCSSValue(val);
                    if (safeProp !== null && safeVal !== null) {
                        css += `  ${safeProp}: ${safeVal} !important;\n`;
                    }
                }
                css += '}\n';
            }

            style.textContent = css;
        },

        /**
         * Reset all overrides
         */
        reset: () => {
            Injector.state = { variables: {}, selectors: {} };
            const style = document.getElementById(Injector.styleId);
            if (style) {
                style.textContent = '';
            }
        },
    };

    window.Injector = Injector;
})(); // end re-injection guard
